// Generated by packages/clsc/compiler/build.rs from packages/clsc/compiler/src/opcodes.rs. Do not edit.

export const Opcode = {
  Return: 0,
  Line: 1,
  Play: 2,
  PushBool: 3,
  PushFlag: 4,
  Set: 5,
  Not: 6,
  Or: 7,
  And: 8,
  Equal: 9,
  NotEqual: 10,
  Jump: 11,
  JumpIfFalse: 12,
  Choice: 13,
  LockedChoice: 14,
  Choose: 15,
  PushName: 16,
  PushNone: 17,
  PushTile: 18,
  Command: 19,
  Cg: 20,
} as const

export type Opcode = (typeof Opcode)[keyof typeof Opcode]

// How many u32 operands follow each opcode, indexed by opcode byte.
export const OPERAND_COUNTS: readonly number[] = [0, 3, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 3, 1, 1, 0, 2, 1, 1]
