// Generated by packages/clsc/compiler/build.rs from packages/clsc/compiler/src/opcodes.rs. Do not edit.

export const Opcode = {
  Return: 0,
} as const

export type Opcode = (typeof Opcode)[keyof typeof Opcode]
