use std::fmt::Write as _;

include!("src/opcodes.rs");

const OPCODES_TS: &str = "../vm/src/opcodes.ts";

fn main() {
    println!("cargo:rerun-if-changed=src/opcodes.rs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={OPCODES_TS}");

    let mut ts = String::from(
        "// Generated by packages/clsc/compiler/build.rs from packages/clsc/compiler/src/opcodes.rs. Do not edit.\n\nexport const Opcode = {\n",
    );
    for (byte, name) in OPCODES.iter().enumerate() {
        writeln!(ts, "  {name}: {byte},").unwrap();
    }
    ts.push_str("} as const\n\nexport type Opcode = (typeof Opcode)[keyof typeof Opcode]\n");

    // Rewriting an unchanged file would bump its mtime and wake any file watcher on the VM side.
    if std::fs::read_to_string(OPCODES_TS).ok().as_deref() != Some(ts.as_str()) {
        std::fs::write(OPCODES_TS, ts).expect("write the VM's opcodes.ts");
    }
}
