#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: an Author's crpg setup (docs/guides/crpg.md).
# Run in the content folder: writes GAME_SERVICE_URL and PUBLISH_KEY to its
# .env, which crpg reads, then runs a dry-run Publish.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

# Node reads .env with dotenv quoting, which can't hold the escape write_env gives a single quote.
save() {
  if [[ "$2" == *"'"* ]]; then
    warn "$1 can't contain a single quote ('): crpg couldn't read it back from $ENV_FILE."
    exit 1
  fi
  write_env "$1" "$2"
}

# required ask|ask_secret KEY "Prompt" asks again until KEY has a value.
required() {
  local how="$1" key="$2" prompt="$3"
  "$how" "$key" "$prompt"
  while [[ -z "${!key}" ]]; do
    warn "$key is required."
    "$how" "$key" "$prompt"
  done
}

banner "crpg setup"

stage "Content folder"
say "crpg runs from your content folder: the one holding library/ and worlds/."
if [[ ! -d library || ! -d worlds ]]; then
  warn "$(pwd) has no library/ and worlds/."
  if confirm "Make this the content folder, and create them here?"; then
    mkdir -p library worlds
  else
    say "cd to your content folder, then run this wizard again."
    exit 1
  fi
fi
say "${GREEN}✓${RESET} $(pwd) is a content folder"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && ! git check-ignore -q "$ENV_FILE"; then
  warn "$ENV_FILE will hold the Publish key, and git doesn't ignore it here."
  if confirm "Add $ENV_FILE to .gitignore?"; then
    printf '%s\n' "$ENV_FILE" >> .gitignore
    say "${GREEN}✓${RESET} added $ENV_FILE to .gitignore"
  else
    SKIPPED+=("ignore $ENV_FILE in git before you commit: it holds the Publish key")
  fi
fi
pause

stage "Game Service"
say "Ask your operator for the Game Service's URL and its Publish key."
required ask GAME_SERVICE_URL "Game Service URL (e.g. https://game.example.com):"
# crpg needs the scheme; curl's health check below would quietly add one.
while [[ ! "$GAME_SERVICE_URL" =~ ^https?:// ]]; do
  warn "the URL needs http:// or https://, such as http://$GAME_SERVICE_URL"
  required ask GAME_SERVICE_URL "Game Service URL:"
done
required ask_secret PUBLISH_KEY "Publish key:"
GAME_SERVICE_URL="${GAME_SERVICE_URL%/}"
save GAME_SERVICE_URL "$GAME_SERVICE_URL"
save PUBLISH_KEY "$PUBLISH_KEY"
if command -v curl >/dev/null 2>&1; then
  if curl -fsS --max-time 10 "$GAME_SERVICE_URL/healthz" >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} the Game Service answers"
  else
    warn "no answer from $GAME_SERVICE_URL/healthz: check the URL, or ask your operator."
  fi
fi
pause

stage "Dry run"
if ! command -v crpg >/dev/null 2>&1; then
  warn "crpg isn't installed. Install the Game Service's version of it, then run this wizard again:"
  note "  npm install -g @codeleagues-rpg-engine/cli@<version>"
  SKIPPED+=("crpg publish <world> --dry-run, once crpg is installed")
  pause
else
  say "A dry run checks a World and prints what a Publish would change, uploading nothing."
  worlds=""
  for dir in worlds/*/; do [[ -d "$dir" ]] && worlds+="$(basename "$dir") "; done
  note "Worlds here: ${worlds:-none yet. crpg tiled <world> starts one.}"
  ask WORLD "World to check (Enter skips):"
  if [[ -n "$WORLD" ]]; then
    printf '\n'
    if crpg publish "$WORLD" --dry-run; then
      say "${GREEN}✓${RESET} the setup works: crpg publish $WORLD Publishes it"
    else
      warn "the dry run stopped: fix what it names, then run crpg publish $WORLD --dry-run again."
    fi
  else
    SKIPPED+=("crpg publish <world> --dry-run")
  fi
  pause "Press Enter to finish"
fi

finish
