#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the Game Service operator install (docs/guides/game-service.md).
# Writes every value `serve` reads to .env. By default deploy/compose.yaml also
# runs Postgres and a SeaweedFS bucket (COMPOSE_PROFILES=bundled); with your own,
# it runs `migrate` against them once.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

IMAGE=ghcr.io/palmkonde/codeleagues-rpg-engine-game-service

# Compose and Node read .env with dotenv quoting, which can't hold the escape write_env gives a single quote.
save() {
  if [[ "$2" == *"'"* ]]; then
    warn "$1 can't contain a single quote ('): $ENV_FILE couldn't be read back. Change it, then run the wizard again."
    exit 1
  fi
  write_env "$1" "$2"
}

# required ask|ask_secret KEY "Prompt" asks again until KEY has a value.
required() {
  local how="$1" key="$2" prompt="$3"
  "$how" "$key" "$prompt"
  while [[ -z "${!key}" ]]; do
    warn "$key is required."
    "$how" "$key" "$prompt"
  done
}

# choose "Question" yes|no is a y/n gate whose Enter answers the given default.
choose() {
  local reply="" hint="[y/N]"
  [[ "$2" == yes ]] && hint="[Y/n]"
  printf '  %s? %s %s%s ' "$YELLOW" "$1" "$hint" "$RESET"
  read -r reply || true
  if [[ -z "$reply" ]]; then [[ "$2" == yes ]]; return; fi
  [[ "$reply" =~ ^[Yy] ]]
}

# The secret already saved, so a re-run never rotates it by accident; otherwise 32 fresh random bytes.
secret() {
  _existing "$1" || od -An -tx1 -N32 /dev/urandom | tr -d ' \n'
}

banner "Game Service install"

stage "Image version"
say "Pick the release to run. The client package and crpg are released at the same version."
say "The version is pinned in $ENV_FILE, so the service only upgrades when you change it."
RELEASES=https://api.github.com/repos/Palmkonde/rpg-webbase/releases
newest=$( { curl -fsSL "$RELEASES/latest" 2>/dev/null || curl -fsSL "$RELEASES?per_page=1" 2>/dev/null; } \
  | sed -nE 's/.*"tag_name": *"v([^"]+)".*/\1/p' | head -n1 || true)
current=$(_existing GAME_SERVICE_VERSION || true)
[[ -n "$current" ]] && note "Pinned now: $current"
if [[ -n "$newest" ]] && confirm "Use the newest release, $newest?"; then
  GAME_SERVICE_VERSION="$newest"
else
  [[ -z "$newest" ]] && warn "couldn't look up the newest release; pick one from the releases page."
  open_url "https://github.com/Palmkonde/rpg-webbase/releases"
  required ask GAME_SERVICE_VERSION "Version (e.g. 0.1.0):"
  GAME_SERVICE_VERSION="${GAME_SERVICE_VERSION#v}"
fi
save GAME_SERVICE_VERSION "$GAME_SERVICE_VERSION"

stage "Secrets"
JWT_SECRET=$(secret JWT_SECRET)
PUBLISH_KEY=$(secret PUBLISH_KEY)
save JWT_SECRET "$JWT_SECRET"
save PUBLISH_KEY "$PUBLISH_KEY"
say ""
say "JWT_SECRET signs Student tokens: give it to the Platform developer."
say "PUBLISH_KEY lets crpg Publish: give it to each Author."
note "Both are in $ENV_FILE. Send them over a channel meant for secrets."
note "Running this wizard again keeps them. To rotate one, delete its line from $ENV_FILE first."
pause

stage "Storage"
say "The Game Service keeps World Versions and Flags in Postgres, and World files in an"
say "S3-compatible bucket. deploy/compose.yaml can run both next to it (bundled),"
say "or you can point it at your own."
# Bundled unless an earlier run chose your own.
default=yes
[[ "$(_existing COMPOSE_PROFILES || echo bundled)" == bundled ]] || default=no
if choose "Run Postgres and the bucket in the compose file?" "$default"; then
  BUNDLED=yes
  POSTGRES_PASSWORD=$(secret POSTGRES_PASSWORD)
  save COMPOSE_PROFILES bundled
  save POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
  save DATABASE_URL "postgres://game:$POSTGRES_PASSWORD@postgres:5432/game"
  save S3_ENDPOINT http://seaweedfs:8333
  save S3_BUCKET game
  save S3_REGION us-east-1
  save S3_ACCESS_KEY_ID "$(secret S3_ACCESS_KEY_ID)"
  save S3_SECRET_ACCESS_KEY "$(secret S3_SECRET_ACCESS_KEY)"
  note "Their data lives in the postgres and seaweedfs volumes: back them up."
else
  BUNDLED=no
  save COMPOSE_PROFILES ""
  say ""
  say "Create an empty database and a user that owns it. migrate creates the tables."
  note "Format: postgres://user:password@host:5432/database"
  warn "The container reads this URL, so localhost is the container itself. For a"
  note "  Postgres on this machine, use host.docker.internal (Docker Desktop) or the host's address (Linux)."
  required ask_secret DATABASE_URL "Postgres URL:"
  save DATABASE_URL "$DATABASE_URL"
fi
pause

stage "Bucket"
if [[ "$BUNDLED" == yes ]]; then
  say "The bundled SeaweedFS bucket is set: nothing to ask."
  pause
else
  say "Create a private S3-compatible bucket first: the Game Service never creates one."
  say "Its access key needs ListBucket, GetObject, PutObject and DeleteObject on it."
  required ask S3_ENDPOINT "S3 endpoint (e.g. https://s3.eu-west-1.amazonaws.com):"
  required ask S3_BUCKET "Bucket name:"
  required ask S3_REGION "Region (e.g. eu-west-1; R2 takes auto):"
  required ask S3_ACCESS_KEY_ID "Access key id:"
  required ask_secret S3_SECRET_ACCESS_KEY "Secret access key:"
  save S3_ENDPOINT "$S3_ENDPOINT"
  save S3_BUCKET "$S3_BUCKET"
  save S3_REGION "$S3_REGION"
  save S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
  save S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
fi

stage "Platforms"
say "The origins of the Platform pages that mount the game, comma-separated."
required ask CORS_ORIGINS "CORS_ORIGINS (e.g. https://learn.example.com):"
save CORS_ORIGINS "$CORS_ORIGINS"
say ""
say "Behind a CDN, or a proxy that changes the host or scheme, Students fetch World files"
say "from ASSET_BASE_URL. Leave it empty and the service serves them itself."
ask ASSET_BASE_URL "ASSET_BASE_URL (optional):"
if [[ -n "$ASSET_BASE_URL" ]]; then save ASSET_BASE_URL "$ASSET_BASE_URL"; fi

stage "Schema"
say "migrate creates the Game Service's tables. Running it again applies only what's missing."
migrate=(docker run --rm -e DATABASE_URL "$IMAGE:$GAME_SERVICE_VERSION" migrate)
if [[ "$BUNDLED" == yes ]]; then
  say "The bundled Postgres starts with the compose file, and the compose file runs"
  say "migrate before the service every time it starts. Nothing to do now."
elif ! command -v docker >/dev/null 2>&1; then
  warn "docker isn't installed here."
  SKIPPED+=("migrate: ${migrate[*]}")
elif confirm "Run migrate against the database now?"; then
  if DATABASE_URL="$DATABASE_URL" "${migrate[@]}"; then
    say "${GREEN}✓${RESET} the schema is up to date"
  else
    warn "migrate failed: check DATABASE_URL, and that the database is reachable from a container."
    SKIPPED+=("migrate: ${migrate[*]}")
  fi
else
  SKIPPED+=("migrate: ${migrate[*]}")
fi
pause

finish
say "Next: put compose.yaml next to $ENV_FILE and start it:"
say "  curl -fsSLO https://raw.githubusercontent.com/Palmkonde/rpg-webbase/main/deploy/compose.yaml"
say "  docker compose up -d --wait"
printf '\n'
